name: Trigger auto deployment for wahlstedt-tech

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/wahlstedt-tech-AutoDeployTrigger-ad46338a-88c2-4341-84df-8b9e2e07e0a9.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WAHLSTEDTTECH_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: wahlstedtrepository.azurecr.io
          registryUsername: ${{ secrets.WAHLSTEDTTECH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WAHLSTEDTTECH_REGISTRY_PASSWORD }}
          containerAppName: wahlstedt-tech
          resourceGroup: wahlstedt
          imageToBuild: wahlstedtrepository.azurecr.io/wahlstedt-tech:${{ github.sha }}
          dockerfilePath: Dockerfile

     

